version: '3.3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=edp
      - POSTGRES_DB=edp
      - POSTGRES_PASSWORD=pwd
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  web:
    image: gcr.io/edp-backend/backend-api:latest
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=EDP.settings

volumes:
  pgdata:
