# Generated by Django 4.1.7 on 2023-03-25 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("speed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("speed", models.IntegerField()),
                ("limit", models.IntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="speed.vehicle"
                    ),
                ),
            ],
        ),
    ]
