# Generated by Django 4.1.7 on 2023-03-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("speed", "0003_penalty_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penalty",
            name="vehicle",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="speed.vehicle",
            ),
        ),
    ]
