# Generated by Django 4.1.7 on 2023-03-25 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("speed", "0004_alter_penalty_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penalty",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="vehicle",
            field=models.OneToOneField(
                default="MP 20 AA 7106",
                on_delete=django.db.models.deletion.CASCADE,
                to="speed.vehicle",
            ),
        ),
    ]
