# Generated by Django 4.1.7 on 2023-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speed", "0006_alter_penalty_user_alter_penalty_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
