# Generated by Django 4.1.7 on 2023-04-27 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("speed", "0007_alter_userinfo_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="user",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
