name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker with GCR
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gcr.io/edp-backend/backend-api:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Install Docker Compose on GCP Compute instance
      run: |
        gcloud compute ssh edp-instance \
          --zone asia-south1-c \
          --command 'curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose'
        gcloud compute ssh edp-instance \
          --zone asia-south1-c \
          --command 'chmod +x /tmp/docker-compose'
        gcloud compute ssh edp-instance \
          --zone asia-south1-c \
          --command 'sudo mv /tmp/docker-compose /usr/local/bin/docker-compose'

    - name: Copy Repository content to GCP Compute instance
      run: |
        gcloud compute scp {docker-compose.yml,./postgres-init/db_edp.sql} edp-instance:/tmp/ \
          --zone asia-south1-c
    - name: Run docker-compose on GCP Compute instance
      run: |
        gcloud compute ssh edp-instance \
          --zone asia-south1-c \
          --command 'cd /tmp && docker-compose down && docker-compose pull && docker-compose up -d'
